# Generated by Django 3.0.5 on 2020-04-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='credentials_url',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
