# Generated by Django 3.0.5 on 2020-04-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0003_thingrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='thingrule',
            name='action',
            field=models.CharField(default='publish_off', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='thingrule',
            name='rule',
            field=models.CharField(max_length=255),
        ),
    ]
