# Generated by Django 3.0.5 on 2020-04-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thing_name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('iso_timestamp', models.CharField(max_length=255)),
                ('illuminance', models.FloatField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('soil_probe', models.CharField(max_length=255)),
            ],
        ),
    ]
