# Generated by Django 3.0.5 on 2020-04-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='iso_timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='timestamp',
            field=models.IntegerField(),
        ),
    ]
